### ISSUE TITLE
Admin: Can we see the netlify deploys on github?

### ISSUE THREAD

**Issue by novellac** [cherryontech/website#10]
Check into whether we can find a way to see the netlify preview links here on github. Ideally, if we switch to the branch here on Github, we would see a link to "xxxx--cherryontech.netlify.app".

**Comment by Dreamy26** [comment]
https://github.com/netlify/ask-netlify/issues/26

Above is a link of a netlify preview direction

**Comment by novellac** [comment]
Yes I've determined we can see them. When you open a PR, it will create a preview deploy.
![Screen Shot 2020-09-03 at 9 53 19 PM](https://user-images.githubusercontent.com/38117965/92190877-37c94680-ee30-11ea-8e02-a8263469a569.png)
