### ISSUE TITLE
Attach mailing list sign up to homepage button

### ISSUE THREAD

**Issue by novellac** [cherryontech/website#13]
**Context**
This issue is related to #12. There is currently a button "Stay Updated" on the homepage. As of right now, it doesn't have any action attached.

**Next Steps**
Talk to Julieth about how the mailing list form should be implemented (modal dialog? link to outside form?).

**Gotchas**
Possible solutions may be limited by what mailing list provider we choose.

**Comment by julietafb** [comment]
modal dialog is up on figma

**Comment by julietafb** [comment]
I added the modal dialog on zeplin 

https://app.zeplin.io/project/5f26ea0e8d21581f66c1d574/screen/5f440ebf17bd283ef51b82dd/

https://app.zeplin.io/project/5f26ea0e8d21581f66c1d574/screen/5f440ee4db3ae83be0f5ffb8/
