### ISSUE TITLE
Write our bios

### ISSUE THREAD

**Issue by alliequintano** [cherryontech/website#15]
Bios for everyone!

We are filling in this spreadsheet with the bio info (all fields optional!): https://docs.google.com/spreadsheets/d/1A2sTSNm8wZ3swSsl8OQEZyilnwgEHY6wRDxmOUskiqA/edit?usp=sharing

One person will put the content in Forestry from the spreadsheet since we only have one Forestry account. 

Slack convo for reference > https://cherryontech.slack.com/archives/C0184T52GE6/p1597598595009800

**Comment by Dreamy26** [comment]
Added bio information 8/20/20
