### ISSUE TITLE
🍁Happy Hactoberfest! Read on to contribute....🍁

### ISSUE THREAD

**Issue by novellac** [cherryontech/website#151]
# 🍁🍂🎃Welcome to Hacktoberfest 2022! We welcome contributions to our [Tech Dictionary](https://cherryon.tech/dictionary). Here's how to get started:

## 🐱‍💻WHO can contribute?
- People at any level of experience (yep, no experience necessary!)
- People who agree to behave according to our [Code of Conduct](https://github.com/cherryontech/website/blob/pit/CODE_OF_CONDUCT.md)

## 🐱⚽HOW do you contribute?
1. Read through our [Contributing HowTo](https://github.com/cherryontech/website/blob/pit/CONTRIBUTING.md).
1. Find a dictionary entry [on our website](https://cherryon.tech/dictionary/) or submit an entry to be added! You do not need to be assigned an issue - you may make a PR for any dictionary entry you choose. **Kindly note that we will not assign any dictionary entries. You may submit a PR for any [dictionary entry](https://cherryon.tech/dictionary/) that interests you, or even contribute one of your own.**
1. If you don't want to make any commits, you can always [submit an issue](https://github.com/cherryontech/website/issues/new?assignees=&labels=dictionary&template=add_dictionary_entry.md&title=) for it. You don't get Hacktoberfest credit, but we still appreciate the effort!

There are no time limits to contributions. You may contribute during Hacktoberfest, but you are also welcome to contribute any time of the year.

## 🙀💥WHAT to do if you run into trouble?
If you run into any trouble (for example, getting set up or picking a dictionary entry), feel free to [submit a general issue](https://github.com/cherryontech/website/issues/new), and we'll try to help as best we can.

**Comment by mustafaazad03** [comment]
Hello Sir,

I have gone through the repository and the given instructions. I am willing to solve this issue by adding definition of technical terms .I humbly wait for you to assign the task to me on 1st Oct.

**Comment by novellac** [comment]
> Hello Sir,
> 
> I have gone through the repository and the given instructions. I am willing to solve this issue by adding definition of technical terms .I humbly wait for you to assign the task to me on 1st Oct.

Hi, welcome! You're welcome to edit any dictionary entry [on our website](https://cherryon.tech/dictionary/) that you would like to add a definition.

**Comment by mustafaazad03** [comment]
Will I Commit On 1st Oct

**Comment by Dhanshriborse** [comment]
I would like to contribute to this repository. Request you to assign the task of adding definition and perspective to me.

**Comment by RohitRajvaidya5** [comment]
I would like to contribute to this repository. can you assign me on this? or should I make PR without mentioning issue?

**Comment by ofonime41** [comment]
Hi, I've gone through the contribution guide and I'll like to contribute to the project by adding definitions and perspective.

**Comment by Pratt2762** [comment]
Hey, I'm incredibly interested in contributing to this project by adding definitions and perspectives to a number of dictionary entries.

**Comment by novellac** [comment]
> Will I Commit On 1st Oct

You're welcome to commit whenever you like.

**Comment by novellac** [comment]
> I would like to contribute to this repository. Request you to assign the task of adding definition and perspective to me.

@Dhanshriborse You're welcome to find any dictionary entry you like and submit a PR for consideration - no issues will be assigned.

**Comment by novellac** [comment]
> I would like to contribute to this repository. can you assign me on this? or should I make PR without mentioning issue?

@RohitRajvaidya5 You're welcome to make a PR without mentioning issue - choose any dictionary entry you like, or add one of your own.

**Comment by novellac** [comment]
> Hi, I've gone through the contribution guide and I'll like to contribute to the project by adding definitions and perspective.

@ofonime41 You're welcome to find any dictionary entry, or contribute one of your own - no need to wait for an issue.

**Comment by RohitRajvaidya5** [comment]
I have Done PR can you review it.

**Comment by nik132-eng** [comment]
Hey should we assign by some one or directly make PR in this repo?

**Comment by novellac** [comment]
> Hey should we assign by some one or directly make PR in this repo?

Hi @nik132-eng You should take whatever dictionary entry you like and directly make a PR.

**Comment by novellac** [comment]
> I have Done PR can you review it.

@RohitRajvaidya5 Yep we'll be on it! We've had a lot of interest, so we may need a week or two, but we will definitely get to it! :)
