### ISSUE TITLE
Look for someone interested in joining as QA

### ISSUE THREAD

**Issue by alliequintano** [cherryontech/website#17]
@novellac mentioned it would be helpful to have someone testing our work, and it would be a good opportunity for interested/early in their career. 

@alliequintano can act as a mentor for a QA. 

Want our QA to focus on:
- accessibility

Does anyone have someone in mind or have some networks to reach out to?

**Comment by julietafb** [comment]
What are the requirements for being a QA?

**Comment by alliequintano** [comment]
I think we may have discussed last week, but just for reference here: we don't have any requirements in terms of experience for having someone join us as a QA. If you know someone interested in tech but who does not have technical experience (or maybe doesn't know yet what role they would/could perform), this opportunity would be a good entry point. We do want the QA to develop some expertise in accessibility requirements and testing, so the person should be interested in that.

**Comment by novellac** [comment]
We found Cherry Cola!!! Welcome Nia as QA! ❤️ 🍒
