### ISSUE TITLE
Reach out to mentors

### ISSUE THREAD

**Issue by alliequintano** [cherryontech/website#18]
We have discussed looking for mentors to support us in a variety of ways, depending on what the mentor may be best suited for / interested in.

- Individual mentor for our roles
- Group mentor to speak to us in our team meeting and where we could ask questions

We have discussed mentors meeting with us just one time, or on an ongoing basis. We are taking a "More the merrier" attitude :D If you have someone in mind, see what they would feel most comfortable committing to. 

Technical mentors: 
- C#/.NET

**Comment by julietafb** [comment]
I connected with my mentor last Monday, so she is in!! She will try her best to come in to one of our Sunday meetings ( it's a little to early for her 😛)

**Comment by Dreamy26** [comment]
I found a group of new C#.net programmes.. they all seem pretty cool.. will see how this goes..
