### ISSUE TITLE
Contributing Video Tutorial Not Available

### ISSUE THREAD

**Issue by TanyaPina** [cherryontech/website#215]
**Yikes! Briefly, what seems wrong?**
The video tutorial under the "How do I contribute?" section in the CONTRIBUTING.md file is not available anymore.

**Expected Behavior**
This link should take the user to the video tutorial that is hosted on YouTube where they can view it. 

**Current Behavior**
The link does take the user to YouTube, but YouTube shows an error message that says "This video isn't available anymore" instead of the video itself.

**Possible Solution**
Perhaps the video was unlisted, set to private, or moved? 

**Steps to Reproduce**

1. Click on the video link https://www.youtube.com/watch?v=I7WsK5amUTA

**Comment by alliequintano** [comment]
Unfortunately, I could not locate the video.
