### ISSUE TITLE
Pagination on Dictionary page links to wrong base

### ISSUE THREAD

**Issue by novellac** [cherryontech/website#49]
**Yikes! Briefly, what seems wrong?**
When you click to the next page on the `/dictionary`, it goes to the wrong page.

**Expected Behavior**
It should go to `/dictionary/somePageNumber`.

**Current Behavior**
It goes to `/blog/somePageNumber`.

**Possible Solution**
In `Dictionary.vue` replace the `base` property on ln31.

**Steps to Reproduce**
1. Navigate to https://cherryontech.netlify.app/dictionary/
2. Click "next" at the bottom of the page
3. See that the page goes to `/blog/something` instead of `/dictionary/something`

**Comment by alliequintano** [comment]
Nice bug write up :D what are your thoughts on pages rather than keeping it a long list on one page? i have a preference for using cmd+f to search but i imagine there may be some down sides i haven't thought of to that so curious to hear what you were thinking.

**Comment by novellac** [comment]
Yeah ideally I'd also like one long page with a search UI, but haven't put it in yet. I'm worried about page load times, but I think we go the command+f route we'd need some lazy loading on the page content, but I haven't gotten that yet, so pagination is a bit of a compromise. The pagination is in a component so it's pretty easy to remove.
