### ISSUE TITLE
Style homepage

### ISSUE THREAD

**Issue by novellac** [cherryontech/website#7]
Style the homepage according to the Figma file that Julieth sent via Slack.
Assets should be in Figma.

**Comment by julietafb** [comment]
I have an Update for the home page! I added on  Zeplin 
https://zpl.io/2EMLqPv

Notes: Upgrade, a new font for the paragraph, Orbitron and added Astronaut cherry. 
Could we have the Cherry bouncing around the screen?

**Comment by julietafb** [comment]
We unified the lettermark and wordmark logos to one typography style.  So the main logo typography changed! 
To Rubik Mono One
**Zeplin file:** 
https://zpl.io/bPkBKe6
