### ISSUE TITLE
Remove duplicate dictionary entry for "End User"

### ISSUE THREAD

**Issue by ghost** [cherryontech/website#85]
**Yikes! Briefly, what seems wrong?**
There are two dictionary entries for "End User" and "End Users"

**Expected Behavior**
There should only be an entry for one term. We can use "End User" only.

**Current Behavior**
Two of the same terms are listed twice. 

**Possible Solution**
Remove duplicate word of "End Users"

**Steps to Reproduce**
https://deploy-preview-80--cherryontech.netlify.app/dictionary/entry/end-user/
https://deploy-preview-80--cherryontech.netlify.app/dictionary/entry/end-users/

**Comment by Dreamy26** [comment]
Removed End-Users from dictionary.
