### ISSUE TITLE
Content: Credit unsplash

### ISSUE THREAD

**Issue by novellac** [cherryontech/website#9]
We are using an unsplash image for the homepage background and we should give them credit! 
Tasks:
- Ask Julieth where to put this info (usually goes in the footer)
- Check on the unsplash website to see how they suggest we format the attribution

**Comment by cherryOnTechAdmin** [comment]
Suggested credit from unsplash
```<span>Photo by <a href="https://unsplash.com/@andyjh07?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Andy Holmes</a> on <a href="https://unsplash.com/@andyjh07?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>```

**Comment by julietafb** [comment]
Andy Holmes
@andyjh07
https://unsplash.com/photos/rCbdp8VCYhQ

**Comment by novellac** [comment]
@julietafb How should this look? Should I put it at the bottom in a smaller font?

**Comment by julietafb** [comment]
@novellac 
Added Author's name, please add the following  link to his Unsplash page https://unsplash.com/photos/rCbdp8VCYhQ
Please check Zeplin for the update: https://zpl.io/Vkj3Elg

**Comment by andyjh07** [comment]
Just wanted to jump in here and say thank you for using my image, hope it serves your purpose well :)
