### ISSUE TITLE
Remove duplicate dictionary entry for "Heat Map"

### ISSUE THREAD

**Issue by ghost** [cherryontech/website#90]
**Yikes! Briefly, what seems wrong?**
There are two dictionary entries for "Heat Map" and "Heat Maps"

**Expected Behavior**
There should only be an entry for one term. We can use "Heat Map" only.

**Current Behavior**
Two of the same terms are listed twice.

**Possible Solution**
Remove duplicate word of "Heat Maps"

**Steps to Reproduce**
Provide a link to a live example, or an unambiguous set of steps to reproduce the issue.

https://deploy-preview-80--cherryontech.netlify.app/dictionary/entry/heat-map/
https://deploy-preview-80--cherryontech.netlify.app/dictionary/entry/heat-maps/

**Comment by Dreamy26** [comment]
Heat-Maps has been removed from dictionary
